### ISSUE TITLE
src/demo/index.html path and general Directory structure

### ISSUE THREAD

**Issue by eerne** [cdotyone/mochaui#38]
Hi
When browsing to src/demo/index.html all path to scripts and css files are wrong.  Do you use some kind of build script for mochaui, am I missing something?

Would you mind we switch the directory layout to more general MooTools style directory structure?

**Comment by stodge** [comment]
I was wondering the same thing about the structure. The alpha archive includes a build directory that I presume is deployed. This directory doesn't appear to be in git?

**Comment by mui-org** [comment]
Because the demo and build directories are generated I choose not to include them in Git.  I feel this just creates unnecessary commits and changes to the repository.  When I release a new version, I use a Java library I wrote to build the files.  The library can be found at http://github.com/cdotyone/mochaui-build.  I develop using a Grails app that can be found at http://github.com/cdotyone/mochaui-grails that uses the Java library to build the project.   The grails app provides the missing virtual paths you see in the demo source.  This allows me to develop without continuously building Mocha.  The Git is just for the development of Mocha source files not the build artifacts.
If I get enough requests I can include the build and demo directories in the Git, or I will adjust the paths to make more sense to users that do not want to use the Grails app.  Also the mocha-build library is intended to able to run from the command-line, but I have not checked that feature in awhile.  I don't use the command line.  I have everything build into the Grails app.  
If you don't have grails or don't want to use it.  The virtual directories I use are:
mochaui -> mochaui/src/demo
mochaui/scripts -> mochaui/src/demo/scripts
mochaui/scripts/source -> mochaui/src/core
mochaui/themes -> mochaui/src/themes
mochaui/plugins -> mochaui/src/plugins

**Comment by eerne** [comment]
I understand to not include the built script, but the demo/index.html is linking to each script individually (as far as i see), is that correct?

Maybe the demo could be moved out of the src directory anyway. I have seen you mention that in http://groups.google.com/group/mocha-ui/browse_thread/thread/9f45b3011b2550bf

How about a more flat directory structure like:
Demos/
Docs/
Source/
Does it matter to the Grails app build script?

It would be nice if we had everything: Grails app, packager/packager-web support and working Demos. Packager solution would require using YAML headers with dependencies like in mootools-core. Would you mind if i add the YAML?

If so should I work in a new branch "YALM headers" or just on master or develop?

I got a modified version http://github.com/eerne/mochaui http://www.mild.ch/mochaui/Demos/

Thanks for looking into it.
eni

**Comment by eerne** [comment]
There is still some missing image resource path on my fork.

**Comment by mui-org** [comment]
"I understand to not include the built script, but the demo/index.html is linking to each script individually (as far as i see), is that correct?" -
- Actually no that is not correct.  The demo/index.html is built during build process from the src files in src/demo.  The individual scripts are removed and replaced with mocha.js.  Look at the demo/index.html in the last .zip download and you will see what I am saying

Flat directory structure - ok with some caveats
Official Demo needs to use mocha.js not the split out js files.  
Need a version of demo that uses split version to ease development.
-- any ideas on how to reconcile those two competing interests?

As far as building a better packaging system and YAML, I knew that was going to happen.  I just wanted the exercise of building a java library, and did not want to learn an off the shelf packager just yet.   So feel free to take a stab at the YAML.  Develop branch is the one that should be adjusted.  I want the master for the current release, and develop for all sandbox stuff.

**Comment by eerne** [comment]
Thank you for the last commit, now it works nicely with all images, even on IE6!!!

I just got MooTools Core and More running with packager-web (needs a commit by timwienk to ignore version numbers in YAML headers for now). I'll try to add the headers later this night or tomorrow.

Flat directory structure - ok with some caveats
Official Demo needs to use mocha.js not the split out js files.
Need a version of demo that uses split version to ease development.
-- any ideas on how to reconcile those two competing interests?

Just a thought. Maybe the development test file should not be named demos at all. how about a flat structure: Docs/ Plugins/ Source/ Test/ Themes/ 
Could you build it from there and take Test/index.html to build Demo/index.html?

**Comment by mui-org** [comment]
I committed a demo version last night that does not need the virtual directories to develop.  Just point your webserver /src and you can develop from there.
